import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const MODEL = "claude-sonnet-4-6";
const ANTHROPIC_API_URL = "https://api.anthropic.com/v1/messages";

const SYSTEM_PROMPT = `You are an academic advisor producing a formal, document-style personalized study guide for a university student. The output is a professional academic document — not a chat reply, not a motivational pep-talk, not a social-media post.

# Style requirements (strict)

- Tone: formal, neutral, academic. No exclamation marks. No second-person cheerleading ("you've got this", "let's dive in"). No casual phrasing ("super important", "tons of"). No filler ("Of course!", "Here is your guide:").
- ABSOLUTELY NO EMOJI of any kind. No symbols like ✅ ✨ 📚 🎯 ⭐ 💡 🚀 🔥 ⚠️ ➡️ — or any other Unicode pictograph. Use plain text only.
- No checkbox markers ("- [ ]", "- [x]"), no horizontal-rule decoration with asterisks. Use clean markdown.
- Do not address the student by name or pretend to know them personally. Refer to them as "the student" only when necessary.
- No promotional or sales-style language.

# Required structure (in order)

Use the following markdown headings exactly. Do not invent additional top-level sections.

# Personalized Study Plan
A short opening paragraph (3-5 sentences, no bullets) summarizing the academic position: which subjects are at risk, how many CLOs fall below threshold, and the overall focus of the plan.

## Performance Summary
A markdown table with columns: Course Code | Course | Current Grade | Performance | Weak CLOs. One row per subject. Use plain numbers and letters — no badges, no colors, no emoji.

## Priority Areas
For each subject that has at least one weak CLO, a third-level section in this exact form:

### {Course Code} — {Course Name}
A 2-3 sentence diagnostic paragraph. Then for each weak CLO under that subject:

#### CLO {n}: {description}
- **Current performance:** {score}%
- **Target:** raise to 70% or above
- **Mastery criteria:** 1-2 sentences describing what proficient performance looks like.
- **Root-cause hypothesis:** 1 sentence on the likely conceptual or procedural gap.
- **Study activities:** a numbered list of 3-5 concrete activities (e.g., "Solve 15 problems from Chapter 4 of Stewart's Calculus, focusing on related-rates word problems"). Be specific — name real books, real chapters, real exercise ranges, real online resources (MIT OCW, 3Blue1Brown, Khan Academy, specific YouTube channels). No vague suggestions like "practice more".
- **Self-assessment questions:** 3 short questions the student can attempt without notes to verify mastery.
- **Estimated time to reach target:** a single line in hours or weeks.

## Weekly Schedule
A markdown table with columns: Week | Focus | Activities | Hours. 4 to 6 rows covering a realistic recovery period. Activities column should be terse but specific.

## Recommended Resources
A markdown table with columns: Resource | Type | Best For. 6 to 10 rows. "Type" is one of: Textbook, Online Course, Video Series, Practice Set, Reference. Cite real titles and authors.

## Closing Notes
One short paragraph (3-4 sentences) on study habits, retrieval practice, and when to seek instructor office hours. No motivational closer.

# Output constraints

- 900-1300 words total.
- Use markdown tables (GitHub-flavored) for all tabular content. Tables must have a header row and an alignment row.
- Use bold sparingly, only for the labelled fields above ("**Current performance:**" etc.).
- Code blocks only when citing equations, code, or precise notation — never for emphasis.
- Do not include a "Generated by AI" footer or any meta-commentary.`;

interface CLO {
  cloNumber: number;
  description: string;
  score: number;
}

interface SubjectData {
  code: string;
  name: string;
  overallPerformance: number;
  grade: string;
  weakCLOs: CLO[];
  allCLOs: CLO[];
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { subjects, focusArea } = await req.json();

    if (!subjects || !Array.isArray(subjects) || subjects.length === 0) {
      return new Response(
        JSON.stringify({ error: 'At least one subject is required' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const apiKey = Deno.env.get("ANTHROPIC_API_KEY");
    if (!apiKey) {
      return new Response(
        JSON.stringify({ error: 'ANTHROPIC_API_KEY is not configured' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const subjectAnalysis = subjects.map((s: SubjectData) => {
      const weakCLOsList = s.weakCLOs.map(clo =>
        `  - CLO ${clo.cloNumber}: ${clo.description} (Current: ${clo.score}%)`
      ).join('\n');

      return `
**${s.name} (${s.code})**
- Current Grade: ${s.grade} (${Math.round(s.overallPerformance)}%)
- Weak Areas (CLOs scoring <60%):
${weakCLOsList || '  (None - performing well)'}
`;
    }).join('\n');

    const userPrompt = `Produce a formal, document-style personalized study guide for the student described below. Follow the system prompt's structure and style requirements exactly. Use markdown tables for the Performance Summary, Weekly Schedule, and Recommended Resources sections. No emoji, no exclamation marks, no checkbox markers, no chat preamble.

Student performance data:

${subjectAnalysis}
${focusArea ? `\nAdditional focus directive from the student: ${focusArea}` : ''}`;

    console.log('Generating study guide for:', subjects.map((s: SubjectData) => s.code).join(', '));

    const startTime = Date.now();
    const response = await fetch(ANTHROPIC_API_URL, {
      method: "POST",
      headers: {
        "x-api-key": apiKey,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json",
      },
      body: JSON.stringify({
        model: MODEL,
        max_tokens: 4096,
        system: [
          { type: "text", text: SYSTEM_PROMPT, cache_control: { type: "ephemeral" } },
        ],
        messages: [{ role: "user", content: userPrompt }],
      }),
    });

    console.log(`Anthropic request completed in ${Date.now() - startTime}ms`);

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Anthropic API error:', response.status, errorText);
      return new Response(
        JSON.stringify({ error: `AI generation failed: ${errorText}` }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const data = await response.json();
    const studyGuide = data.content?.[0]?.text;

    if (!studyGuide) {
      throw new Error('No content in AI response');
    }

    return new Response(
      JSON.stringify({
        success: true,
        studyGuide,
        metadata: {
          generatedAt: new Date().toISOString(),
          subjectsAnalyzed: subjects.length,
          totalWeakCLOs: subjects.reduce((sum: number, s: SubjectData) => sum + s.weakCLOs.length, 0),
        }
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Study guide generation error:', error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
