import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version',
};

const MODEL = "claude-sonnet-4-6";
const ANTHROPIC_API_URL = "https://api.anthropic.com/v1/messages";

const SYSTEM_PROMPT = `You are an academic curriculum designer producing a formal, document-style supplementary study guide that a university instructor will distribute to a class. The output is a polished academic handout — not a chat reply, not a marketing leaflet, not a motivational message.

# Style requirements (strict)

- Tone: formal, neutral, instructional. No exclamation marks. No first-person teacher-voice ("I think you'll find…"). No casual phrasing. No filler ("Of course!", "Here is the guide:").
- ABSOLUTELY NO EMOJI of any kind. No symbols like ✅ ✨ 📚 🎯 ⭐ 💡 🚀 🔥 ⚠️ ➡️ — or any other Unicode pictograph. Plain text only.
- No checkbox markers ("- [ ]", "- [x]"). Use clean markdown.
- Address the audience as "students" in the third person, not "you", except inside the optional "For the Instructor" notes.
- No promotional or motivational language. The document should read like a printed university handout.

# Required structure (in order)

Use the following markdown headings exactly.

# Course Study Guide
A short opening paragraph (3-5 sentences, no bullets) stating which CLOs the class is struggling with and the overall focus of this supplementary material.

## Class Performance Overview
A markdown table with columns: Course Code | Course | Class Average | Weak CLOs. One row per course included.

## Topics Requiring Additional Study
For each weak CLO, a third-level section:

### {Course Code} — CLO {n}: {description}
- **Class average:** {score}%
- **Concept overview:** 2-4 sentences explaining the underlying concept in clear academic language a student can read on their own. Include any prerequisite knowledge.
- **Worked example:** a brief textual walkthrough of a representative problem or scenario (no need for diagrams). If the topic is non-quantitative, a short illustrative case in its place.
- **Practice activities:** a numbered list of 3-5 specific exercises or problem sources (e.g., "Stewart's Calculus, 8th ed., Section 4.2, problems 12-28 odd"). Cite real materials.
- **Self-check questions:** 3 short questions students can attempt without notes.
- **Recommended study time:** a single line in hours.
- **For the instructor:** 1-2 sentences on common misconceptions and a suggested in-class intervention. This is the only place where second-person "you" addressing the instructor is acceptable.

## Suggested Weekly Plan
A markdown table with columns: Week | Topics | Practice | Hours. 4-6 rows covering a realistic remediation period.

## Recommended Resources
A markdown table with columns: Resource | Type | Best For. 6-10 rows. "Type" is one of: Textbook, Online Course, Video Series, Practice Set, Reference. Cite real titles and authors.

## Assessment Recovery Strategy
A short paragraph (3-5 sentences) describing how students can use this guide alongside the current course schedule, including suggested checkpoints and signs the material has been mastered. No motivational closer.

# Output constraints

- 1000-1400 words total.
- Use GitHub-flavored markdown tables for all tabular content. Each table must have a header row and an alignment row.
- Use bold only for labelled fields ("**Class average:**", "**Concept overview:**", etc.).
- Code blocks only for equations, code, or precise notation.
- Do not include a "Generated by AI" footer or meta-commentary.`;

interface CLO {
  cloNumber: number;
  description: string;
  score: number;
  assessmentType: string;
}

interface SubjectData {
  code: string;
  name: string;
  classAverage: number;
  weakCLOs: CLO[];
  allCLOs: CLO[];
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { subjects, focusArea } = await req.json();

    if (!subjects || !Array.isArray(subjects) || subjects.length === 0) {
      return new Response(
        JSON.stringify({ error: 'At least one subject is required' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const apiKey = Deno.env.get("ANTHROPIC_API_KEY");
    if (!apiKey) {
      return new Response(
        JSON.stringify({ error: 'ANTHROPIC_API_KEY is not configured' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const subjectAnalysis = subjects.map((s: SubjectData) => {
      const weakCLOsList = s.weakCLOs.map(clo =>
        `  - CLO ${clo.cloNumber}: ${clo.description} (Class Average: ${Math.round(clo.score)}%)`
      ).join('\n');

      return `
**${s.name} (${s.code})**
- Class Average: ${Math.round(s.classAverage)}%
- Weak Areas (CLOs where the class averages below 60%):
${weakCLOsList || '  (None - class is performing well)'}
`;
    }).join('\n');

    const userPrompt = `Produce a formal, document-style study guide that the instructor will distribute to students. Follow the system prompt's structure and style requirements exactly. Use markdown tables for the Class Performance Overview, Suggested Weekly Plan, and Recommended Resources sections. No emoji, no exclamation marks, no checkbox markers, no chat preamble.

Class performance data:

${subjectAnalysis}
${focusArea ? `\nAdditional focus directive from the instructor: ${focusArea}` : ''}`;

    console.log('Generating teacher study guide for:', subjects.map((s: SubjectData) => s.code).join(', '));

    const response = await fetch(ANTHROPIC_API_URL, {
      method: "POST",
      headers: {
        "x-api-key": apiKey,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json",
      },
      body: JSON.stringify({
        model: MODEL,
        max_tokens: 4096,
        system: [
          { type: "text", text: SYSTEM_PROMPT, cache_control: { type: "ephemeral" } },
        ],
        messages: [{ role: "user", content: userPrompt }],
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Anthropic API error:', response.status, errorText);
      return new Response(
        JSON.stringify({ error: `AI generation failed: ${errorText}` }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const data = await response.json();
    const studyGuide = data.content?.[0]?.text;

    if (!studyGuide) throw new Error('No content in AI response');

    return new Response(
      JSON.stringify({
        success: true,
        studyGuide,
        metadata: {
          generatedAt: new Date().toISOString(),
          subjectsAnalyzed: subjects.length,
          totalWeakCLOs: subjects.reduce((sum: number, s: SubjectData) => sum + s.weakCLOs.length, 0),
        }
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Teacher study guide error:', error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
